# Python 15

```python
from abc import *

class Animal:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    @abstractmethod
    def sleep(self):
        pass
    @abstractmethod
    def eat(self):
        pass
```

```python
from Py02_05.Animal import Animal

class Cat(Animal):
    def __init__(self,name,age,color):
        super().__init__(name,age)
        self.color = color
    def sleep(self):
        print("야옹거리며 잔다")
    def eat(self):
        print("츄르먹는다.")
    def color(self):
        print(f"{self.color}색이다.")
```

```python
from Py02_05.Animal import Animal

class Dog(Animal):
    def bark(self):
        print(f"{self.name}이/가 멍멍 짖습니다.")
    def sleep(self):
        print("쿨쿨쿨")
    def eat(self):
        print("쩝쩝")

d1 = Animal("징징",23)
d1.sleep()
```

```python
class MyMinusException(Exception):
    def __str__(self):
        return '음수 입력!'
```

```python
class MyWrException(Exception):
    def __str__(self):
        return 'a가 b보다 클 수 없음!'
```

```python
from time import sleep

from Dog import Dog
from Cat import Cat

d1 = Dog("코코",2)
d1.bark()
d1.sleep()
d1.eat()

c1 = Cat("야옹",11,"하얀색")
c1.sleep()
c1.eat()
c1.color()
```

```python
try:
    a = int(input("a는?"))
    b = int (input("b는?"))
    c = a/b
    print(c)
except:
    print("잘못됐습니다!")
print("프로그램 끝")
```

```python
# finally : exit 등이 호출되어 프로그램이 종료되거나
# return 키워드 통해서 함수가 종료되도
# 반드시 해당 부분을 실행함

# print("Hello")
# exit()
# print("world")

# try:
#     a = 10
#     b = 0
#     c = a/b
# except:
#     print("잘못된 나눗셈")
#     exit()
# finally:
#     print("무조건 이건 실행하고 끝남")
# print("나눗셈 프로그램 끝")

print("----------- 01 문제 -----------")
# try:
#     a = int(input("a는?"))
#     b = int(input("b는?"))
#     sum = 0
#     for i in range(a, b + 1):
#         sum += i
#     print(sum)
# except:
#     print("잘못된 입력")

print("----------- 02 문제 -----------")
# def aTobSum():
#     sum = 0
#     try:
#         a = input("a는?")
#         b = input("b는?")
#         a = int(a)
#         b = int(b)
#         for i in range(a, b + 1):
#             sum += i
#     except:
#         print("이상한 값 입력함!")
#         return -1
#     finally: # try가 다실행되든 안되는 finally는 무조건 다 실행
#        print(f"a의 값 : {a}")
#        print(f"b의 값 : {b}")
#     return sum
# result = aTobSum()
# print(result)

print("----------- 03 문제 -----------")
def aTobSumRec(a,b):
    if a==b+1:
        return 0
    return a+aTobSumRec(a+1,b)
    #return b+aTobSumRec(b-1)
try:
    a = int(input('a?'))
    b = int(input('b?'))
    sum = aTobSumRec(a,b)
    print(sum)
except ValueError as e:
    print('값 입력 오류')
except RecursionError as e:
    print('무한 호출')
except Exception as e:
    print(f' 모르겠음 하여튼 에러! {e}' )

print("----------- 04 문제 -----------")
from Py02_05.MyMinusException import MyMinusException
from Py02_05.MyWrException import MyWrException

sum = 0
try:
    a = int(input('a?'))
    b = int(input('b?'))
    if a<0 or b<0:
        raise MyMinusException()
    if a>b:
        raise MyWrException()
    for item in range(a,b+1):
        sum+=item
    print(sum)
except MyMinusException as e:
    if a<0:
        a*=-1
    if b<0:
        b*=-1
    for item in range(a,b+1):
        sum+=item
except MyWrException as e:
    temp = a
    a = b
    b = temp
    for item in range(a,b+1):
        sum+=item
except Exception as e:
    print(f'그 외의 오류! {e}')

print(sum)

```